# This is a basic workflow to help you get started with Actions

name: Cover

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      working-directory: ./cover

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
  
    - name: installing packages
      run: npm install
      working-directory: ${{env.working-directory}}
 
    - name: linting
      run: npm run lint
      working-directory: ${{env.working-directory}}
      
      
    - name: building
      run: npm run build --prod
      working-directory: ${{env.working-directory}}
      
    - name: testing
      run: npm run test
      working-directory: ${{env.working-directory}}
    
    - name: deploy
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.COVER_AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'cover/dist'
        working-directory: ${{env.working-directory}}
